### ISSUE TITLE
Disconnected by the server due to the huge amount of lost package messages

### ISSUE THREAD

**Issue by niko-chiu** [pion/ion-sfu#370] opened 2021-01-08 03:36 UTC
### Your environment.
  - Version: v1.7.6
  - Browser: Latest Chrome, Firefox, iOS Safari
  - Other Information - 

### What did you do?
Deployed on GCP.
All devices have a good internet connection, upload and download speed have +80 Mbps.
The resolution set to shd and using simulcast.
Has a turn server.

### What did you expect?
Don't get disconnect by the server.

### What happened?
I am new to webrtc and deployed the ion-sfu on GCP. I got a lot of lost packets messages after the connection has established and then the clients got disconnected by the server after a while.
![Screenshot 2021-01-08 at 11 08 16 AM](https://user-images.githubusercontent.com/8285612/103970343-fdd3cc80-51a2-11eb-8427-cd4460a35629.png)

**Comment by OrlandoCo** [comment] 2021-01-08 04:21
@niko-chiu thxs for the opening an issue, it's really hard for us to know the reason of packet loss:

- The server is near the clients?
- Are you connecting many clients through wifi and on same network?
- Are you using ion-sfu turn or coturn or other?
- Can you share a webrtc dump?
- Can you reproduce this issue with non simulcast and lower resolution?

**Comment by niko-chiu** [comment] 2021-01-08 05:43
@OrlandoCo Thanks for the response  :)
- I pinged the server and got the response within ~15ms. SFU server, turn server and clients are in the same country.
- No. three clients on my mac with a wired connection and a mobile phone was using wifi 
- I use conturn
- [webrtc_internals_dump.txt](https://github.com/pion/ion-sfu/files/5785394/webrtc_internals_dump.txt)
- I can reproduce this issue with non simulcast. Lower resolution does help extend the connection time before got disconnected by the server, but I want to do it in HD or higher

**Comment by OrlandoCo** [comment] 2021-01-08 17:43
@niko-chiu That error was fixed on latest release, please upgrade.

Can you try testing without turn, or use ion-sfu turn?

**Comment by niko-chiu** [comment] 2021-01-09 11:54
@OrlandoCo I have tried to run the gallerytest example and found out even in the local env the sfu server still logging a lot of lost packets messages. Is this normal?

![image](https://user-images.githubusercontent.com/8285612/104090860-678fcb80-52b4-11eb-8585-c3b1f6a5b61c.png)

**Comment by OrlandoCo** [comment] 2021-01-09 17:49
@niko-chiu No we have never seen this issue before, in localhost you should not lose any packets, not sure what the problema can be, but is not related to SFU

**Comment by tarrencev** [comment] 2021-01-10 21:22
Closing for now since this is likely not sfu related

**Closed by tarrencev** 2021-01-10 21:22 UTC
Labels: bug
